apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: qualys-crs-staging

namespace: qualys-system

commonLabels:
  environment: staging

resources:
  - ../../base

# In staging, enable enforcement for critical policies only
patchesStrategicMerge:
  - enforce-critical.yaml

patches:
  - target:
      kind: TracingPolicy
    patch: |-
      - op: add
        path: /metadata/labels/environment
        value: staging
      - op: add
        path: /metadata/annotations/policy.qualys.com~1enforcement-mode
        value: selective-enforcement
