apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: crs-block-ingress-file-copy
  labels:
    generated-by: qualys-crs
    qualys.com/rule-id: Launch_Ingress_Remote_File_Copy_Tools_in_Container_T1105
    mitre.attack/technique: T1105
    mitre.attack/tactic: command-and-control
    policy.qualys.com/severity: high
    policy.qualys.com/action: block
  annotations:
    description: Detect ingress file transfer tools
spec:
  kprobes:
  - call: sys_execve
    syscall: true
    args:
    - index: 0
      type: string
    selectors:
    - matchArgs:
      - index: 0
        operator: Postfix
        values:
        - /curl
        - /wget
        - /ftp
        - /tftp
        - /nc
      matchActions:
      - action: Sigkill
