apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: qualys-crs-dev

namespace: qualys-system

commonLabels:
  environment: dev

resources:
  - ../../base

# In dev, we only use detection (audit) mode - no enforcement
# All policies use action: Post by default

patches:
  - target:
      kind: TracingPolicy
    patch: |-
      - op: add
        path: /metadata/labels/environment
        value: dev
      - op: add
        path: /metadata/annotations/policy.qualys.com~1enforcement-mode
        value: audit-only
